### ISSUE TITLE
您好，我想咨询下这个项目的celery是怎么运行的？

### ISSUE THREAD

**Issue by uname-yang** [felinx/d3status#2]
我没有找到入口，具体和tornado怎么整合的？
谢谢您了

**Comment by felinx** [comment]
见tasks目录的相关文件，可以追一下代码里的 status_tasks，另外要看一下celery是怎么运行的。

**Comment by uname-yang** [comment]
我有点不理解，您这只有一个config，tornado项目是怎么把worker启动的呢？

**Comment by felinx** [comment]
celery根据config来运行worker的，是单独运行的，跟tornado没关，worker和发送消息的task部分代码是共用的。

**Comment by uname-yang** [comment]
我用celery起tasks.py 启动出错啊
`
(celery)yang@debiand:~/WorkPath/celery/Tornado-Seed/tasks$ celery -A tasks worker --loglevel=info
Traceback (most recent call last):
  File "/home/yang/.virtualenvs/celery/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/home/yang/.virtualenvs/celery/local/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/home/yang/.virtualenvs/celery/local/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/home/yang/.virtualenvs/celery/local/lib/python2.7/site-packages/celery/bin/celery.py", line 770, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/yang/.virtualenvs/celery/local/lib/python2.7/site-packages/celery/bin/base.py", line 309, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/home/yang/.virtualenvs/celery/local/lib/python2.7/site-packages/celery/bin/base.py", line 469, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/home/yang/.virtualenvs/celery/local/lib/python2.7/site-packages/celery/bin/base.py", line 489, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/home/yang/.virtualenvs/celery/local/lib/python2.7/site-packages/celery/app/utils.py", line 246, in find_app
    found = sym.celery
AttributeError: 'module' object has no attribute 'celery'
`

**Comment by felinx** [comment]
mysql、redis环境配置ok的话，在tasks目录直接运行celeryd即可

**Comment by uname-yang** [comment]
谢谢您的回答，可以启动了，我也在做一些调整。
1.我还想问一下您这个项目的data层是怎么设计的？
2tornado的异步非堵塞和数据库的驱动的阻塞操作怎么处理

最近正在学习您的框架，谢谢

**Comment by felinx** [comment]
data层是直接写sql的，数据库的驱动的阻塞操作问题不用去管它，要优先优化数据库查询性能，不要做复杂的多表操作，实际项目时可以起多个tornado进程

**Comment by uname-yang** [comment]
了解，谢谢您
